version: "3.4"
services:
  mongo-db:
    image: mongo
    networks:
      - mongo_db_net
    ports:
      - "27017:27017"
    container_name: "mongodb-container"
    environment:
      - MONGO_INITDB_DATABASE=demodb  
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    networks:
      - mongo_db_net
    ports:
      - "8081:8081"
    container_name: "mongo-express-container"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb-container
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    depends_on:
      - mongo-db
    links:
      - mongo-db
networks:
  mongo_db_net:
    driver: "bridge"