server:
  port: 8888
spring:  data:    mongodb:
      host: localhost
      port: 27017      database: demodb
      username: root
      password: password
      authentication-database: admin